import React from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from './MainLayout.module.css'
import { NavBar } from '../NavBar';
const inter = Inter({ subsets: ['latin'] })

const MainLayouts = ({children}:{children:JSX.Element}) => {  
    return (
        <div className={`${styles.container}`}>
          <Head>
            <title>Home-LFM</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <NavBar/>
          <main className={`${styles.main} ${inter.className}`}>
            {children}
          </main>
        </div>
      )
}

export default MainLayouts